[query]
QUERY_TEMPLATE = """ Task: Generate a syntactically correct MSSQL Graph query to answer the user’s question.
Instructions:
Use only the tables, columns, and relationships provided in the schema to construct the query.
Avoid using any tables, columns, or relationships not listed in the schema.

Schema:
{schema}

Guidelines:
- Only reference the columns explicitly provided in the schema.
- Avoid ambiguous column references by fully qualifying table and column names.
- Use the LIKE operator for filtering text fields instead of an exact match with '='.
- Only include columns in the SELECT clause that directly answer the question and that are used in any filtering conditions.
- Ensure correct edge (relationship) directionality in the query syntax.
- Only create SELECT queries; do not include any commands that modify the database.
- Do not use GROUP BY statements in the query.
- Use IS NULL or IS NOT NULL for checking missing values in columns.
- If performing division, ensure the denominator is filtered to exclude zero.
- Use table and column aliases as needed for clarity and readability.
- Structure complex queries with WITH statements if necessary to create temporary subsets.
- Use `$node_id`, `$from_id` and `$to_id` parameters to generate query

Important:
- Avoid using SELECT *; explicitly include only necessary columns in SELECT statements.
- Ensure that all referenced columns exist within the specified schema.
- Tailor the output to answer the user’s question with the most relevant information.
- Only use WITH statements for temporary subsets; ensure all SELECT statements are single-line where possible.

Now, based on these guidelines, generate a query to answer the question:
Question: {question}
Generated Graph Query:
"""

[response_generation]
FINAL_RESPONSE_GENERATION_PROMPT = """
You are an agent who will be provided with the user_input and the MsSQL Graph Query execution response from Database. You will have to generate the response based on those data.

History: {history}
User Input: {user_input}
MsSQL Graph Query Response: {graph_query_response}

Make the response natural and precise.
"""

[sql_correction]
CORRECT_TABLE_COLUMN_TEMPLATE = """
You are an expert {dialect} graph expert. You are provided an MsSQL graph that tries to answer the user's question.
However, it has some errors. You need to correct this {dialect} graph query.

Question:
{question}

Incorrect SQL Query:
{prev_query}

Error in Query:
{suggestions}

Only use these graph schemas as context to fix the query:
{schema}

IMPORTANT NOTE:
- Only generate the correct MsSQL graph query without any comments.

Corrected Query:
"""
